Fix linting error
Error: "'v-for' directives require 'v-bind:key' directives". Ideally the
keys would be unique IDs to avoid re-rendering of items in case the list
is modified. It doesn't really matter in this case as the list is
static so the item index is used.